import {
    House, 
    DollarSign, 
    PiggyBank, 
    ScrollText, 
    Settings, 
    Headset, 
    UserRound, 
    ChartNoAxesColumn, 
    ArrowRightLeft, 
    Home,
    MoveRight,
    ChevronUp,
    ChevronDown,
    Pencil,
} from 'lucide-react';

export const icons = {
    house: House,
    dollarSign: DollarSign,
    piggyBank: PiggyBank,
    scrollText: ScrollText,
    settings: Settings,
    headset: Headset,
    userRound: UserRound,
    chartNoAxesColumn: ChartNoAxesColumn,
    arrowRightLeft: ArrowRightLeft,
    home: Home,
    moveRight: MoveRight,
    chevronUp: ChevronUp,
    chevronDown: ChevronDown,
    pencil: Pencil,
};